dotenv: .env

wallets:
  from_key: ${PRIVATE_KEY}

subscriptions:
  chainlink: ${CHAINLINK_SUBSCRIPTION_ID}

ipfs:
  overwrite_metadata: False
  upload_type: pinata # pinata | ipfs
  # these pinata keys can make 500 calls
  pinata_key: ${PINATA_API_KEY}
  pinata_secret: ${PINATA_API_SECRET}
  pinata_jwm: Bearer ${PINATA_JWT}

dependencies:
  # - <organizzation/repo>@<version> scaricate da GitHub
  - smartcontractkit/chainlink-brownie-contracts@0.4.1
  - smartcontractkit/chainlink@1.2.1
  - OpenZeppelin/openzeppelin-contracts@4.7.1

compiler:
  # instruct the compiler that @chainlink points to GitHub
  solc:
    remappings:
      - '@brownie-cl=smartcontractkit/chainlink-brownie-contracts@0.4.1'
      - '@chainlink=smartcontractkit/chainlink@1.2.1'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.7.1'



networks:
  default: development
  development: 
    keyhash: '0xd89b2bf150e3b9e13446986e571fb9cab24b13cea0a43ea20a6049a85cc807cc'
    verify: False
  ganache: 
    verify: False
  mainnet-fork:
    eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
    verify: False
  rinkeby:
    vrf_coordinator: '0x6168499c0cFfCaCD319c818142124B7A15E857ab'
    link_token: '0x01BE23585060835E02B77ef475b0Cc51aA1e0709'
    keyhash: '0xd89b2bf150e3b9e13446986e571fb9cab24b13cea0a43ea20a6049a85cc807cc'
    verify: True
  kovan:
    weth_token: '0xd0A1E359811322d97991E03f863a0C30C2cF029C'
    fau_token: '0xFab46E002BbF0b4509813474841E0716E6730136'
    eth_usd_feed: '0x9326BFA02ADD2366b30bacB125260Af641031331'
    dai_usd_feed: '0x777A68032a88E5A84678A77Af2CD65A7b3c0775a'
    verify: True
  goerli:
    verify: True