dotenv: .env

wallets:
  from_key: ${PRIVATE_KEY}

subscriptions:
  chainlink: ${CHAINLINK_SUBSCRIPTION_ID}

ipfs:
  overwrite_metadata: False
  upload_type: pinata # pinata | ipfs
  # these pinata keys can make 500 calls
  pinata_key: ${PINATA_API_KEY}
  pinata_secret: ${PINATA_API_SECRET}
  pinata_jwm: Bearer ${PINATA_JWT}

dependencies:
  # - <organizzation/repo>@<version> scaricate da GitHub
  - smartcontractkit/chainlink-brownie-contracts@0.2.1
  - smartcontractkit/chainlink@1.2.1
  - OpenZeppelin/openzeppelin-contracts@4.7.1

compiler:
  # instruct the compiler that @chainlink points to GitHub
  solc:
    remappings:
      - '@brownie-cl=smartcontractkit/chainlink-brownie-contracts@0.2.1'
      - '@chainlink=smartcontractkit/chainlink@1.2.1'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.7.1'



networks:
  default: development
  development: 
    keyhash: '0xd89b2bf150e3b9e13446986e571fb9cab24b13cea0a43ea20a6049a85cc807cc'
  mainnet-fork:
    eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
    verify: False
  rinkeby:
    vrf_coordinator: '0x6168499c0cFfCaCD319c818142124B7A15E857ab'
    link_token: '0x01BE23585060835E02B77ef475b0Cc51aA1e0709'
    keyhash: '0xd89b2bf150e3b9e13446986e571fb9cab24b13cea0a43ea20a6049a85cc807cc'
    verify: True
  goerli:
    verify: True